/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSearchIndexRouteImport } from './routes/_app/search/index'
import { Route as AppSongsSongIdRouteImport } from './routes/_app/songs/$songId'
import { Route as AppSearchQueryRouteImport } from './routes/_app/search/$query'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSearchIndexRoute = AppSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSongsSongIdRoute = AppSongsSongIdRouteImport.update({
  id: '/songs/$songId',
  path: '/songs/$songId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSearchQueryRoute = AppSearchQueryRouteImport.update({
  id: '/search/$query',
  path: '/search/$query',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/search/$query': typeof AppSearchQueryRoute
  '/songs/$songId': typeof AppSongsSongIdRoute
  '/search': typeof AppSearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/search/$query': typeof AppSearchQueryRoute
  '/songs/$songId': typeof AppSongsSongIdRoute
  '/search': typeof AppSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/search/$query': typeof AppSearchQueryRoute
  '/_app/songs/$songId': typeof AppSongsSongIdRoute
  '/_app/search/': typeof AppSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search/$query' | '/songs/$songId' | '/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search/$query' | '/songs/$songId' | '/search'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/search/$query'
    | '/_app/songs/$songId'
    | '/_app/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/search/': {
      id: '/_app/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/songs/$songId': {
      id: '/_app/songs/$songId'
      path: '/songs/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof AppSongsSongIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/search/$query': {
      id: '/_app/search/$query'
      path: '/search/$query'
      fullPath: '/search/$query'
      preLoaderRoute: typeof AppSearchQueryRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppSearchQueryRoute: typeof AppSearchQueryRoute
  AppSongsSongIdRoute: typeof AppSongsSongIdRoute
  AppSearchIndexRoute: typeof AppSearchIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppSearchQueryRoute: AppSearchQueryRoute,
  AppSongsSongIdRoute: AppSongsSongIdRoute,
  AppSearchIndexRoute: AppSearchIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
